export const projects = [
  {
    name: "Flora",
    githubUrl: "https://github.com/Siratul804/Flora_Native",
    image: "../../assets/mob.png",
    youtube: false,
    youtubeUrl: "",
    category: ["mob"],
    projectUrl: "https://github.com/Siratul804/Flora_Native",
    deployed: true,
  },
  {
    name: "EZPromt AI ",
    githubUrl: "https://github.com/Siratul804/prompt_nextJS",
    image: "../../assets/ez.PNG",
    youtube: false,
    youtubeUrl: "",
    category: ["full", "font", "back"],
    projectUrl: "https://ezprompt.vercel.app/",
    deployed: true,
  },
  {
    name: "e Temp User",
    githubUrl: "https://github.com/Siratul804/success_e-commerce_server.git",
    image: "../../assets/e.png",
    projectUrl: "https://e-temp.netlify.app/",
    category: ["full", "font", "back"],
    deployed: true,
  },
  {
    name: "e Temp Admin Dashboard",
    githubUrl: "https://github.com/Siratul804/success_e-commarce_admin",
    image: "../../assets/etempA.png",
    projectUrl: "https://e-temp-admin.netlify.app/",
    category: ["full", "font", "back"],
    deployed: true,
  },

  {
    name: "Easy Devilery User",
    githubUrl: "https://github.com/Siratul804/Easy_Delivery_server",
    image: "../../assets/del.png",
    projectUrl: "https://easydeliverys.netlify.app/",
    category: ["full", "font", "back"],
    deployed: true,
  },
  {
    name: "Easy Devilery Admin Dashboard",
    githubUrl: "https://github.com/Siratul804/Easy_Delivery_admin",
    image: "../../assets/easyA.png",
    projectUrl: "https://easydeliveryadmin.netlify.app/",
    category: ["full", "font", "back"],
    deployed: true,
  },

  {
    name: "Seed to BIG",
    githubUrl: "/#",
    image: "../../assets/seed.png",
    projectUrl: "https://seedtobig.org/",
    deployed: true,
    category: ["full", "font", "back"],
  },

  {
    name: "Estheticbd",
    githubUrl: "#",
    image: "../../assets/es.png",
    projectUrl: "https://estheticbd.vercel.app/",
    deployed: true,
    category: ["font"],
  },
  {
    name: "Ami Kintu",
    githubUrl: "https://github.com/Siratul804/ami_kintu_moha_khadok",
    image: "../../assets/ami.png",
    projectUrl: "https://ami-kintu-moha-khadok.vercel.app/",
    category: ["full", "font", "back"],
    deployed: true,
  },
  {
    name: "Dr.Muhibbur Rahman",
    githubUrl: "#",
    image: "../../assets/doc.png",
    projectUrl: "https://drmuhibbur.netlify.app/",
    category: ["font"],
    deployed: true,
  },
  {
    name: "stb Solution",
    githubUrl: "#",
    image: "../../assets/dummy.png",
    deployed: true,
    projectUrl: "https://epic-stonebraker-d0f036.netlify.app/",
    category: ["font"],
  },
];
